import React from "react";
import Head from "next/head";
import {
  Header,
  CarouselImage,
  CarouselProduct,
  Advantage,
  ProductCard,
  Banner,
  Footer,
  Container,
} from "@/components";

import Link from "next/link";

import styles from "../public/styles/Home.module.css";

import { productCards, mockData } from "../utils/mock.js";

export default function Home() {
  return (
    <>
      <Head>
        <title>Вкусезона</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <main className={styles.main}>
          <CarouselImage slides={mockData} isPagination={false} />
          <CarouselProduct title={"Популярные товары"}>
            {productCards.map((product, id) => {
              return (
                <a
                  href={`products/${product.path}`}
                  key={product.imageAlt && id}
                >
                  <ProductCard
                    image_path__mini={product.image_path__mini}
                    imageAlt={product.imageAlt}
                    price={product.price}
                    discount={product.discount}
                    tagName={product.tagName}
                  />
                </a>
              );
            })}
          </CarouselProduct>
          <Advantage />
          <CarouselProduct title={"Самое выгодное сегодня"}>
            {productCards.map((product, id) => {
              return (
                <ProductCard
                  key={product.imageAlt && id}
                  image_path__mini={product.image_path__mini}
                  imageAlt={product.imageAlt}
                  price={product.price}
                  discount={product.discount}
                  tagName={product.tagName}
                />
              );
            })}
          </CarouselProduct>
          <Banner />
          <CarouselProduct title={"Без сахара"}>
            {productCards.map((product, id) => {
              return (
                <ProductCard
                  key={product.imageAlt && id}
                  image_path__mini={product.image_path__mini}
                  imageAlt={product.imageAlt}
                  price={product.price}
                  discount={product.discount}
                  tagName={product.tagName}
                />
              );
            })}
          </CarouselProduct>
        </main>
      </Container>
      <Footer />
    </>
  );
}
