import Head from "next/head";
import Header from "components/Header";
import CarouselImage from "components/CarouselImage";
import ProductCard from "components/ProductCard";
import CarouselProduct from "components/CarouselProduct";

import styles from "../public/styles/Home.module.css";

const mockData = [
  "/images/hero_image.png",
  "/images/hero_image.png",
  "/images/hero_image.png",
];

const productCards = [
  {
    imageUrl: "/images/product_card.png",
    imageAlt: "паштет",
    price: 400,
    discount: 0,
  },
  {
    imageUrl: "/images/product_card__2.png",
    imageAlt: "не паштет",
    price: 200,
    discount: 10,
  },
  {
    imageUrl: "/images/product_card.png",
    imageAlt: "паштет",
    price: 400,
    discount: 0,
  },
  {
    imageUrl: "/images/product_card__2.png",
    imageAlt: "не паштет",
    price: 200,
    discount: 10,
  },
  {
    imageUrl: "/images/product_card.png",
    imageAlt: "паштет",
    price: 400,
    discount: 0,
  },
  {
    imageUrl: "/images/product_card__2.png",
    imageAlt: "не паштет",
    price: 200,
    discount: 10,
  },
  {
    imageUrl: "/images/product_card.png",
    imageAlt: "паштет",
    price: 400,
    discount: 0,
  },
  {
    imageUrl: "/images/product_card__2.png",
    imageAlt: "не паштет",
    price: 200,
    discount: 10,
  },
  {
    imageUrl: "/images/product_card.png",
    imageAlt: "паштет",
    price: 400,
    discount: 0,
  },
  {
    imageUrl: "/images/product_card__2.png",
    imageAlt: "не паштет",
    price: 200,
    discount: 10,
  },
  {
    imageUrl: "/images/product_card.png",
    imageAlt: "паштет",
    price: 400,
    discount: 0,
  },
  {
    imageUrl: "/images/product_card__2.png",
    imageAlt: "не паштет",
    price: 200,
    discount: 10,
  },
];
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Вкусезона</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <CarouselImage imgUrls={mockData} />
        <div className={"d-flex--column"}>
          <CarouselProduct>
            {productCards.map((product, id) => {
              return (
                <ProductCard
                  key={product.imageAlt && id}
                  imageUrl={product.imageUrl}
                  imageAlt={product.imageAlt}
                  price={product.price}
                  discount={product.discount}
                />
              );
            })}
          </CarouselProduct>
        </div>
      </main>
    </div>
  );
}
